# Generated by Django 5.2.10 on 2026-01-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_name', models.CharField(max_length=100, verbose_name='Proxmox nodename')),
            ],
            options={
                'verbose_name': 'Proxmox node',
                'verbose_name_plural': 'Proxmox nodes',
                'ordering': ('id',),
            },
        ),
    ]
