# Generated by Django 5.2.10 on 2026-01-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm',
            name='pm_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Proxmox token'),
        ),
    ]
