# Generated by Django 5.2.10 on 2026-01-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_pm_pm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm',
            name='pm_ip_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proxmox ip address'),
        ),
    ]
