# Generated by Django 5.2.10 on 2026-05-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_pm_pm_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm',
            name='pm_order_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Proxmox order number'),
        ),
    ]
